### ISSUE TITLE
Link issue- social media icons are not exactly link

### ISSUE THREAD

**Issue by merinpriyasha** [LuminiNanayakkara/Resume#4]
![Resume1](https://user-images.githubusercontent.com/68733175/149185592-3edce2ea-103d-4013-b5ed-6cfe62fb9e16.png)

* In this page social media icons are not exactly linked with your personal profile.
* I think it is a good idea to link this icons with your social media accounts(If you have) correctly, so that web user can connect with you through your social media account

**Comment by LuminiNanayakkara** [comment]
I created it as links
